apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-{{ .Values.application.release }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx
        image: mirror.gcr.io/nginx:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /usr/share/nginx/html
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config-{{ .Values.configmap.version }}
